### ISSUE TITLE
Add few more programs before HotNets deadline

### ISSUE THREAD

**Issue by taegyunkim** [chipmunk-project/chipmunk_experiments#6]

**Comment by XiangyuG** [comment]
**Find two programs, flowlets and stateful_fw**
time iterative_solver /tmp/stateful_fw_canonicalized_equivalent_0.sk example_alus/pred_raw.stateful_alu stateless_alus/stateless_alu.j2 4 5 10 --parallel-sketch

time iterative_solver /tmp/flowlets_canonicalized_equivalent_0.sk example_alus/pred_raw.stateful_alu stateless_alus/stateless_alu.j2 4 5 10 --parallel-sketch

**Comment by XiangyuG** [comment]
**Find one more benchmark**
time iterative_solver /tmp/trTCM_sat_core_canonicalized_equivalent_0.sk example_alus/nested_ifs.stateful_alu stateless_alus/stateless_alu.j2 3 3 10 --parallel-sketch

**Comment by XiangyuG** [comment]
**Find one more benchmark trTCM_sat_core**
time iterative_solver /tmp/trTCM_sat_core_canonicalized_equivalent_0.sk example_alus/nested_ifs.stateful_alu stateless_alus/stateless_alu.j2 3 3 10 --parallel-sketch

**Comment by taegyunkim** [comment]
trTCM_unsat_core might also work.

**Comment by XiangyuG** [comment]
trTCM_unsat_core does not work even for domino. Actually, after discussing with Anirudh, both trTCM_unsat_core and trTCM_sat_core are part of the trTCM so they are not actually being used. We can forget these two and just focus on other 8 programs for experiments.

**Comment by anirudhSK** [comment]
We have 8 programs now, which should be sufficient for the time being. Closing this issue.
